# Generated by Django 6.0.3 on 2026-03-17 04:00

from django.db import migrations, models


def migrate_location_to_tags(apps, schema_editor):
    JobListing = apps.get_model("core", "JobListing")
    LocationTag = apps.get_model("core", "LocationTag")

    for listing in JobListing.objects.exclude(location__isnull=True).exclude(location=""):
        tag, _ = LocationTag.objects.get_or_create(name=listing.location)
        listing.locations.add(tag)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="joblisting",
            name="locations",
            field=models.ManyToManyField(blank=True, to="core.locationtag"),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("intern", "Intern"),
                    ("temporary", "Temporary"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="team",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="updated_at_source",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="workplace_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_site", "On-site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(
            migrate_location_to_tags,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="location",
        ),
    ]
