# Generated by Django 6.0.3 on 2026-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_enrich_listing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
