# Generated by Django 6.0.3 on 2026-03-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_expired_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblisting",
            name="country",
        ),
        migrations.AddField(
            model_name="locationtag",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="locationtag",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="locationtag",
            name="region_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
