# Generated by Django 6.0.5 on 2026-05-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_seed_companies_workday_bamboohr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="platform",
            field=models.CharField(
                choices=[
                    ("greenhouse", "Greenhouse"),
                    ("lever", "Lever"),
                    ("ashby", "Ashby"),
                    ("workday", "Workday"),
                    ("bamboohr", "BambooHR"),
                    ("phenom", "Phenom People"),
                ],
                max_length=20,
            ),
        ),
    ]
