# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_seed_companies_phenom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="platform",
            field=models.CharField(
                choices=[
                    ("greenhouse", "Greenhouse"),
                    ("lever", "Lever"),
                    ("ashby", "Ashby"),
                    ("workday", "Workday"),
                    ("bamboohr", "BambooHR"),
                    ("phenom", "Phenom People"),
                    ("jibe", "Jibe"),
                ],
                max_length=20,
            ),
        ),
    ]
