/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health check
         * @description Returns a static OK response when the service is up.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate and start a session
         * @description Authenticates with username and password, then creates a server-side session cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Invalidates the current server-side session and clears the security context.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the currently-authenticated user
         * @description Returns basic identity information for the user associated with the current session.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all sources
         * @description Returns every source configured for ingestion. Not paginated — the list is small (< 100 entries).
         */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List job listings with filter, sort, and pagination
         * @description The core jobs endpoint. Supports a recursive filter DSL, multi-field
         *     sorting (including the user-specific `seen` sort), and page-based
         *     pagination.
         */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Faceted aggregations for jobs
         * @description Returns distinct value counts for the requested facet fields. Filters
         *     from the same query are applied (so facets reflect the current view).
         */
        get: operations["getJobFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a job as seen by the current user
         * @description Idempotent — re-marking has no effect.
         */
        post: operations["markJobSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all location tags
         * @description Returns every geocoded `LocationTag`. Not paginated.
         */
        get: operations["listLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ingestion run history (most recent first)
         * @description Returns a paginated list of ingestion runs for the current user, ordered by newest run first.
         */
        get: operations["listRuns"];
        put?: never;
        /**
         * Trigger a new ingestion run
         * @description Spawns ingestion asynchronously. Returns the created `Run` immediately with status PENDING.
         */
        post: operations["triggerRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single run
         * @description Returns one ingestion run by id when it belongs to the current user.
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current user's saved views
         * @description Returns saved views owned by the current user, ordered by name.
         */
        get: operations["listSavedViews"];
        put?: never;
        /**
         * Create a new saved view for the current user
         * @description Persists the current user's filter, sort, column, and page-size preferences as a named saved view.
         */
        post: operations["createSavedView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Get a saved view by id
         * @description Returns one saved view by id when it belongs to the current user.
         */
        get: operations["getSavedView"];
        /**
         * Replace a saved view
         * @description Replaces a saved view owned by the current user with the supplied preferences.
         */
        put: operations["updateSavedView"];
        post?: never;
        /**
         * Delete a saved view
         * @description Deletes a saved view owned by the current user.
         */
        delete: operations["deleteSavedView"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "status": "ok"
         *     }
         */
        HealthStatus: {
            /** @enum {string} */
            status: "ok";
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        CurrentUser: {
            /** Format: int64 */
            id: number;
            username: string;
            firstName?: string;
            lastName?: string;
            /** Format: email */
            email?: string;
            isStaff: boolean;
            isSuperuser: boolean;
        };
        /**
         * @description RFC 7807 Problem Details.
         * @example {
         *       "type": "about:blank",
         *       "title": "Bad Request",
         *       "status": 400,
         *       "detail": "Sort field unknown: foo"
         *     }
         */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Per-field validation errors (for 422 responses). */
            errors?: {
                field: string;
                message: string;
            }[];
        };
        /** @enum {string} */
        SourcePlatform: "GREENHOUSE" | "LEVER" | "ASHBY" | "WORKDAY" | "BAMBOOHR" | "PHENOM" | "JIBE";
        Source: {
            /** Format: int64 */
            id: number;
            name: string;
            platform: components["schemas"]["SourcePlatform"];
            boardId: string;
            isActive: boolean;
        };
        LocationTag: {
            /** Format: int64 */
            id: number;
            name: string;
            countryCode?: string | null;
            regionCode?: string | null;
            city?: string | null;
            /** @description Derived hierarchical key (country / region / city). */
            geoKey?: string | null;
        };
        /** @enum {string} */
        ListingStatus: "ACTIVE" | "EXPIRED";
        JobListing: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            sourceId: number;
            sourceName: string;
            externalId: string;
            title: string;
            /** Format: uri */
            url: string;
            status: components["schemas"]["ListingStatus"];
            locations: components["schemas"]["LocationTag"][];
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            updatedAtSource?: string | null;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiredAt?: string | null;
            /** @description Whether the current user has marked this listing as seen. */
            seen: boolean;
        };
        JobListingPage: {
            items: components["schemas"]["JobListing"][];
            page: number;
            pageSize: number;
            total: number;
            hasNext: boolean;
        };
        MarkSeenResponse: {
            /** Format: int64 */
            id: number;
            seen: boolean;
        };
        /**
         * @description Fields filterable via the DSL. Department, team, employment_type,
         *     and workplace_type are intentionally excluded — not reliably populated
         *     across sources.
         * @enum {string}
         */
        FilterField: "title" | "location" | "source_name" | "status" | "country" | "region" | "city" | "published_at" | "first_seen_at" | "last_seen_at";
        /** @enum {string} */
        FilterOperator: "contains" | "not_contains" | "eq" | "neq" | "in" | "not_in" | "is_empty" | "is_not_empty" | "before" | "after" | "in_last_days";
        FilterPredicate: {
            field: components["schemas"]["FilterField"];
            op: components["schemas"]["FilterOperator"];
            /** @description Operator value. Null for `is_empty`/`is_not_empty`; array for `in`/`not_in`; integer days for `in_last_days`; string for others. */
            value?: unknown;
        };
        /**
         * @description Recursive filter tree. A node is one of:
         *     - a single predicate (`{field, op, value}`)
         *     - `{and: [Expr, ...]}`
         *     - `{or: [Expr, ...]}`
         *     - `{not: Expr}`
         */
        FilterExpression: components["schemas"]["FilterPredicate"] | {
            and: components["schemas"]["FilterExpression"][];
        } | {
            or: components["schemas"]["FilterExpression"][];
        } | {
            not: components["schemas"]["FilterExpression"];
        };
        FacetBucket: {
            value: string;
            count: number;
        };
        /**
         * @description Map of facet field → buckets. Keys are limited to the values
         *     documented on `getJobFacets`.
         * @example {
         *       "source_name": [
         *         {
         *           "value": "Acme",
         *           "count": 42
         *         },
         *         {
         *           "value": "Beta",
         *           "count": 7
         *         }
         *       ],
         *       "status": [
         *         {
         *           "value": "ACTIVE",
         *           "count": 100
         *         }
         *       ]
         *     }
         */
        FacetsResponse: {
            [key: string]: components["schemas"]["FacetBucket"][];
        };
        /** @enum {string} */
        RunStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
        Run: {
            /** Format: int64 */
            id: number;
            status: components["schemas"]["RunStatus"];
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            sourcesProcessed: number;
            listingsCreated: number;
            listingsUpdated: number;
            listingsExpired: number;
            errorMessage?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            page: number;
            pageSize: number;
            total: number;
            hasNext: boolean;
        };
        /** @description Optional payload to scope a triggered run to a single source. */
        TriggerRunRequest: {
            /** Format: int64 */
            sourceId?: number | null;
        };
        SortSpec: {
            field: string;
            /** @enum {string} */
            dir: "asc" | "desc";
        };
        ColumnDef: {
            id: string;
            visible: boolean;
            width?: number | null;
        };
        SavedView: {
            /** Format: int64 */
            id: number;
            name: string;
            filterExpression?: components["schemas"]["FilterExpression"];
            columns: components["schemas"]["ColumnDef"][];
            sort: components["schemas"]["SortSpec"][];
            /** @description Free-form per-view config (page size, density, etc.). */
            config?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SavedViewCreateRequest: {
            name: string;
            filterExpression?: components["schemas"]["FilterExpression"];
            columns: components["schemas"]["ColumnDef"][];
            sort: components["schemas"]["SortSpec"][];
            config?: {
                [key: string]: unknown;
            };
        };
        SavedViewUpdateRequest: components["schemas"]["SavedViewCreateRequest"];
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Validation failed */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Zero-based page index. */
        PageParam: number;
        /** @description Page size. */
        PageSizeParam: number;
        /**
         * @description Multi-field sort. Comma-separated `field:dir` tokens, e.g.
         *     `first_seen_at:desc,title:asc`. The pseudo-field `seen` sorts by
         *     whether the current user has marked the listing as seen.
         */
        SortParam: string[];
        /**
         * @description Recursive filter DSL, JSON-encoded. See `FilterExpression`.
         *     Example: `{"and":[{"field":"status","op":"eq","value":"ACTIVE"},{"field":"published_at","op":"in_last_days","value":7}]}`
         */
        FilterParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; session cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 1,
                     *         "name": "Acme",
                     *         "platform": "GREENHOUSE",
                     *         "boardId": "acme",
                     *         "isActive": true
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Source"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description Zero-based page index. */
                page?: components["parameters"]["PageParam"];
                /** @description Page size. */
                pageSize?: components["parameters"]["PageSizeParam"];
                /**
                 * @description Multi-field sort. Comma-separated `field:dir` tokens, e.g.
                 *     `first_seen_at:desc,title:asc`. The pseudo-field `seen` sorts by
                 *     whether the current user has marked the listing as seen.
                 */
                sort?: components["parameters"]["SortParam"];
                /**
                 * @description Recursive filter DSL, JSON-encoded. See `FilterExpression`.
                 *     Example: `{"and":[{"field":"status","op":"eq","value":"ACTIVE"},{"field":"published_at","op":"in_last_days","value":7}]}`
                 */
                filter?: components["parameters"]["FilterParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated job listings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListingPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getJobFacets: {
        parameters: {
            query: {
                /**
                 * @description Recursive filter DSL, JSON-encoded. See `FilterExpression`.
                 *     Example: `{"and":[{"field":"status","op":"eq","value":"ACTIVE"},{"field":"published_at","op":"in_last_days","value":7}]}`
                 */
                filter?: components["parameters"]["FilterParam"];
                /** @description Comma-separated list of facet fields to aggregate. */
                fields: ("source_name" | "status" | "country" | "region" | "city")[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Facet buckets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    markJobSeen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mark recorded (or already present) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkSeenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location tag list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationTag"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Zero-based page index. */
                page?: components["parameters"]["PageParam"];
                /** @description Page size. */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    triggerRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TriggerRunRequest"];
            };
        };
        responses: {
            /** @description Run accepted */
            202: {
                headers: {
                    /** @description URL of the created run resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSavedViews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved views (ordered by name) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedViewCreateRequest"];
            };
        };
        responses: {
            /** @description Saved view created */
            201: {
                headers: {
                    /** @description URL of the created saved view */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedViewUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated saved view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    deleteSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
